name: Scala CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          version: "v0.1.15"
          fail_ci_if_error: true
